//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wintellect.Analyzers {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wintellect.Analyzers.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to a method using a param aray as arguments &apos;{0}&apos;.
        /// </summary>
        internal static string AvoidCallingMethodsWithParamArgsAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AvoidCallingMethodsWithParamArgsAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid calling methods with param array arguments.
        /// </summary>
        internal static string AvoidCallingMethodsWithParamArgsAnalyzerTitle {
            get {
                return ResourceManager.GetString("AvoidCallingMethodsWithParamArgsAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert &apos;{0}&apos; to the explicit type &apos;{1}&apos;.
        /// </summary>
        internal static string AvoidPreDefinedTypesAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AvoidPreDefinedTypesAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use explicit types instead of predefined to avoid confusion.
        /// </summary>
        internal static string AvoidPreDefinedTypesAnalyzerTitle {
            get {
                return ResourceManager.GetString("AvoidPreDefinedTypesAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never use the single parameter Debug.Assert.
        /// </summary>
        internal static string CallAssertMethodsWithMessageParameterAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CallAssertMethodsWithMessageParameterAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always use Debug.Assert methods that have a message parameter.
        /// </summary>
        internal static string CallAssertMethodsWithMessageParameterAnalyzerTitle {
            get {
                return ResourceManager.GetString("CallAssertMethodsWithMessageParameterAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting.
        /// </summary>
        internal static string CategoryFormatting {
            get {
                return ResourceManager.GetString("CategoryFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        internal static string CategoryPerformance {
            get {
                return ResourceManager.GetString("CategoryPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        internal static string CategoryUsage {
            get {
                return ResourceManager.GetString("CategoryUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; statements must have braces.
        /// </summary>
        internal static string IfAndElseMustHaveBracesAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("IfAndElseMustHaveBracesAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If and else statements must use braces.
        /// </summary>
        internal static string IfAndElseMustHaveBracesAnalyzerTitle {
            get {
                return ResourceManager.GetString("IfAndElseMustHaveBracesAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enclose statement in braces.
        /// </summary>
        internal static string IfAndElseMustHaveBracesCodeFixProviderActionMessage {
            get {
                return ResourceManager.GetString("IfAndElseMustHaveBracesCodeFixProviderActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method name {0} should be renamed {0}Async.
        /// </summary>
        internal static string ReturningTaskRequiresAsyncAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("ReturningTaskRequiresAsyncAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Task or Task&lt;T&gt; returning method names must end with Async.
        /// </summary>
        internal static string ReturningTaskRequiresAsyncAnalyzerTitle {
            get {
                return ResourceManager.GetString("ReturningTaskRequiresAsyncAnalyzerTitle", resourceCulture);
            }
        }
    }
}
